from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.internal_tasks import normalize_task_analysis_method_selection, validate_task_analysis_contract
from app.tasking import TaskAnalysis


class PlannerContractExamplesTests(unittest.TestCase):
    def test_multilingual_examples_validate_against_the_planner_contract(self) -> None:
        examples = [
            {
                "contract_version": "tripletex.task_analysis.v1",
                "objective": "Register a travel expense report",
                "method_name": "RunTravelExpenseWorkflow",
                "method_arguments": {
                    "title": "Kundenbesuch Trondheim",
                    "employeeEmail": "elias.hoffmann@example.org",
                    "departureDate": "2026-03-01",
                    "returnDate": "2026-03-05",
                    "perDiemRate": 800,
                    "perDiemCount": 5,
                    "expenses": [
                        {"description": "Flugticket", "amount": 6300},
                        {"description": "Taxi", "amount": 250},
                    ],
                },
                "missing_required_arguments": [],
                "task_family": "travelexpense.create",
                "operation": "create",
                "target_resource": "travelExpense",
                "detected_language": "German",
                "search_hints": {"employeeEmail": "elias.hoffmann@example.org"},
                "payload_fields": {"title": "Kundenbesuch Trondheim", "departureDate": "2026-03-01", "returnDate": "2026-03-05"},
                "attachment_required": False,
                "ambiguity_notes": [],
                "risk_level": "low",
                "completion_signals": ["A travel expense is created."],
                "notes": [],
            },
            {
                "contract_version": "tripletex.task_analysis.v1",
                "objective": "Delete a travel expense report",
                "method_name": "RunTravelExpenseWorkflow",
                "method_arguments": {
                    "title": "Conference Stavanger",
                    "employeeEmail": "hugo.martin@example.org",
                    "departureDate": "2026-03-10",
                    "returnDate": "2026-03-14",
                },
                "missing_required_arguments": [],
                "task_family": "travelexpense.delete",
                "operation": "delete",
                "target_resource": "travelExpense",
                "detected_language": "French",
                "search_hints": {"employeeEmail": "hugo.martin@example.org"},
                "payload_fields": {"title": "Conference Stavanger", "departureDate": "2026-03-10", "returnDate": "2026-03-14"},
                "attachment_required": False,
                "ambiguity_notes": [],
                "risk_level": "high",
                "completion_signals": ["The travel expense is deleted."],
                "notes": [],
            },
            {
                "contract_version": "tripletex.task_analysis.v1",
                "objective": "Create an employee from an employment contract",
                "method_name": "RunEmployeeOnboardingWorkflow",
                "method_arguments": {
                    "firstName": "Miguel",
                    "lastName": "Costa",
                    "email": "miguel.costa@example.org",
                    "dateOfBirth": "1981-11-06",
                    "nationalIdentityNumber": "06118185755",
                    "bankAccountNumber": "63096583860",
                    "departmentName": "Innkjøp",
                    "occupationCode": "4110",
                    "annualSalary": 720000,
                    "percentageOfFullTimeEquivalent": 100,
                    "startDate": "2026-04-01",
                    "employmentForm": "Fast stilling",
                    "remunerationType": "Fastlønn (månedlig)",
                },
                "missing_required_arguments": [],
                "task_family": "employee.create",
                "operation": "create",
                "target_resource": "employee",
                "detected_language": "Portuguese",
                "search_hints": {"email": "miguel.costa@example.org", "nationalIdentityNumber": "06118185755"},
                "payload_fields": {"departmentName": "Innkjøp", "occupationCode": "4110", "annualSalary": 720000},
                "attachment_required": True,
                "ambiguity_notes": [],
                "risk_level": "low",
                "completion_signals": ["The employee is created from the contract."],
                "notes": [],
            },
            {
                "contract_version": "tripletex.task_analysis.v1",
                "objective": "Create internal projects from the largest expense-account increases",
                "method_name": "RunExpenseIncreaseProjectWorkflow",
                "method_arguments": {
                    "baselineDateFrom": "2026-01-01",
                    "baselineDateTo": "2026-01-31",
                    "comparisonDateFrom": "2026-02-01",
                    "comparisonDateTo": "2026-02-28",
                    "topCount": 3,
                    "isInternal": True,
                    "createActivity": True,
                },
                "missing_required_arguments": [],
                "task_family": "project.create",
                "operation": "other",
                "target_resource": "project",
                "detected_language": "Spanish",
                "search_hints": {
                    "baselineDateFrom": "2026-01-01",
                    "baselineDateTo": "2026-01-31",
                    "comparisonDateFrom": "2026-02-01",
                    "comparisonDateTo": "2026-02-28",
                },
                "payload_fields": {"isInternal": True, "createActivity": True},
                "attachment_required": False,
                "ambiguity_notes": [],
                "risk_level": "medium",
                "completion_signals": ["Three projects and activities are created."],
                "notes": [],
            },
            {
                "contract_version": "tripletex.task_analysis.v1",
                "objective": "Perform month-end closing for March 2026",
                "method_name": "RunMonthEndClosingWorkflow",
                "method_arguments": {
                    "voucherDate": "2026-03-31",
                    "periodizationAmount": 9750,
                    "prepaidAccountNumber": "1710",
                    "periodizationExpenseAccountNumber": "6500",
                    "depreciationAmount": 2665.28,
                    "depreciationExpenseAccountNumber": "6030",
                    "depreciationAccumulatedAccountNumber": "1290",
                    "payrollAccrualAmount": 50000,
                    "payrollExpenseAccountNumber": "5000",
                    "payrollLiabilityAccountNumber": "2900",
                    "verifyTrialBalance": True,
                },
                "missing_required_arguments": [],
                "task_family": "ledger.month_end",
                "operation": "create",
                "target_resource": "ledger",
                "detected_language": "Nynorsk",
                "search_hints": {"voucherDate": "2026-03-31"},
                "payload_fields": {"verifyTrialBalance": True},
                "attachment_required": False,
                "ambiguity_notes": [],
                "risk_level": "high",
                "completion_signals": ["Month-end vouchers are posted and checked."],
                "notes": [],
            },
            {
                "contract_version": "tripletex.task_analysis.v1",
                "objective": "Enable department accounting",
                "method_name": "RunCompanyOpenAPIWorkflow",
                "method_arguments": {"moduleDepartmentAccounting": True},
                "missing_required_arguments": [],
                "task_family": "department.enable_module",
                "operation": "update",
                "target_resource": "company",
                "detected_language": "English",
                "search_hints": {},
                "payload_fields": {"moduleDepartmentAccounting": True},
                "attachment_required": False,
                "ambiguity_notes": [],
                "risk_level": "medium",
                "completion_signals": ["Department accounting is enabled."],
                "notes": [],
            },
            {
                "contract_version": "tripletex.task_analysis.v1",
                "objective": "Register outgoing invoice payment",
                "method_name": "RegisterInvoicePayment",
                "method_arguments": {
                    "customerName": "Havbris AS",
                    "customerOrganizationNumber": "887674973",
                    "paidAmount": 17724,
                    "invoiceAmount": 17724,
                    "currencyCode": "EUR",
                    "paymentDate": "2026-03-21",
                },
                "missing_required_arguments": [],
                "task_family": "invoice.register_payment",
                "operation": "register_payment",
                "target_resource": "invoice",
                "detected_language": "Norwegian",
                "search_hints": {"customerName": "Havbris AS", "customerOrganizationNumber": "887674973"},
                "payload_fields": {"paidAmount": 17724, "currencyCode": "EUR"},
                "attachment_required": False,
                "ambiguity_notes": [],
                "risk_level": "medium",
                "completion_signals": ["The invoice payment is registered."],
                "notes": [],
            },
            {
                "contract_version": "tripletex.task_analysis.v1",
                "objective": "Run payroll for Jules Leroy for March 2026",
                "method_name": "RunSalaryPayrollWorkflow",
                "method_arguments": {
                    "employeeEmail": "jules.leroy@example.org",
                    "date": "2026-03-31",
                    "month": 3,
                    "year": 2026,
                    "salaryLines": [
                        {"salaryTypeName": "Fastlønn", "amount": 56950},
                        {"salaryTypeName": "Bonus", "amount": 9350},
                    ],
                },
                "missing_required_arguments": [],
                "task_family": "salary.create",
                "operation": "create",
                "target_resource": "salary",
                "detected_language": "French",
                "search_hints": {"employeeEmail": "jules.leroy@example.org"},
                "payload_fields": {"date": "2026-03-31", "month": 3, "year": 2026},
                "attachment_required": False,
                "ambiguity_notes": [],
                "risk_level": "medium",
                "completion_signals": ["A salary transaction is created for the employee."],
                "notes": [],
            },
            {
                "contract_version": "tripletex.task_analysis.v1",
                "objective": "Reconcile bank statement entries against invoices",
                "method_name": "RunBankReconciliationWorkflow",
                "method_arguments": {
                    "fromDate": "2026-03-01",
                    "toDate": "2026-03-31",
                    "statementEntries": [
                        {
                            "entryId": "line-1",
                            "paymentDate": "2026-03-21",
                            "direction": "incoming",
                            "amount": 17724,
                            "invoiceNumber": "2026-1042",
                            "customer": {
                                "customerName": "Havbris AS",
                                "organizationNumber": "887674973",
                            },
                        }
                    ],
                },
                "missing_required_arguments": [],
                "task_family": "bank.reconcile",
                "operation": "other",
                "target_resource": "bank",
                "detected_language": "English",
                "search_hints": {"fromDate": "2026-03-01", "toDate": "2026-03-31"},
                "payload_fields": {"statementEntries": [{"entryId": "line-1"}]},
                "attachment_required": True,
                "ambiguity_notes": [],
                "risk_level": "high",
                "completion_signals": ["Matching customer and supplier invoice payments are registered."],
                "notes": [],
            },
        ]

        for raw_example in examples:
            with self.subTest(language=raw_example["detected_language"], method=raw_example["method_name"]):
                analysis = TaskAnalysis.model_validate(raw_example)
                validate_task_analysis_contract(analysis)
                normalized = normalize_task_analysis_method_selection(task_analysis=analysis)
                self.assertEqual(normalized.method_name, raw_example["method_name"])


if __name__ == "__main__":
    unittest.main()
