from __future__ import annotations

import argparse
import itertools
import shutil
import statistics
import sys
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parent
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from ngd_utils import image_records_by_id, load_json, resolve_image_path, save_json
from score_submission_run import evaluate_predictions, run_submission


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Evaluate the packaged submission path over repeated CV splits.")
    parser.add_argument("annotations", type=Path, help="Path to annotations.json")
    parser.add_argument("images_dir", type=Path, help="Directory containing the shelf images")
    parser.add_argument("submission_dir", type=Path, help="Submission directory containing run.py and weights")
    parser.add_argument(
        "--cv-manifest",
        type=Path,
        default=Path("data/splits/cv/default/manifest.json"),
        help="Path to a CV manifest generated by make_cv_splits.py, or its containing directory.",
    )
    parser.add_argument(
        "--workspace",
        type=Path,
        default=Path("data/interim/cv_sweep"),
        help="Workspace for staged fold inputs and predictions.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("data/reports/cv_submission_sweep.json"),
        help="Where to write the aggregated sweep report JSON.",
    )
    parser.add_argument(
        "--confidence-thresholds",
        nargs="+",
        type=float,
        help="One or more top-level confidence_threshold values to try.",
    )
    parser.add_argument(
        "--nms-iou-thresholds",
        nargs="+",
        type=float,
        help="One or more ONNX NMS IoU thresholds to try.",
    )
    parser.add_argument(
        "--classifier-score-alphas",
        nargs="+",
        type=float,
        help="One or more classifier score_alpha values to try.",
    )
    parser.add_argument(
        "--prototype-alphas",
        nargs="+",
        type=float,
        help="One or more classifier prototype_alpha values to try.",
    )
    parser.add_argument(
        "--prototype-temperatures",
        nargs="+",
        type=float,
        help="One or more classifier prototype_temperature values to try.",
    )
    parser.add_argument(
        "--rejector-enabled-values",
        nargs="+",
        type=int,
        choices=(0, 1),
        help="Whether to disable or enable the classifier rejector. Use 0 and/or 1.",
    )
    parser.add_argument("--max-configs", type=int, help="Optional cap on the number of candidate configs to evaluate.")
    parser.add_argument("--copy-images", action="store_true", help="Copy staged fold images instead of hardlinking them.")
    parser.add_argument("--iou-threshold", type=float, default=0.5, help="IoU threshold for local scoring.")
    parser.add_argument(
        "--python-executable",
        type=Path,
        help="Optional Python interpreter to use for submission/run.py instead of the current one.",
    )
    parser.add_argument(
        "--pythonpath",
        action="append",
        type=Path,
        default=[],
        help="Optional extra PYTHONPATH entry for local scoring. Repeatable.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    annotations_path = args.annotations.resolve()
    images_dir = args.images_dir.resolve()
    submission_dir = args.submission_dir.resolve()
    workspace = args.workspace.resolve()
    workspace.mkdir(parents=True, exist_ok=True)

    cv_manifest_path = resolve_manifest_path(args.cv_manifest.resolve())
    cv_manifest = load_json(cv_manifest_path)
    split_entries = [normalize_split_entry(cv_manifest_path.parent, entry) for entry in cv_manifest.get("splits", [])]
    if not split_entries:
        raise SystemExit(f"No splits found in manifest: {cv_manifest_path}")

    coco = load_json(annotations_path)
    images_by_id = image_records_by_id(coco)
    fold_inputs = stage_fold_inputs(
        split_entries=split_entries,
        images_by_id=images_by_id,
        images_dir=images_dir,
        workspace=workspace / "inputs",
        copy_images=args.copy_images,
    )

    config_path = submission_dir / "submission_config.json"
    base_config = load_submission_config(config_path)
    candidates = build_candidates(
        base_config=base_config,
        confidence_thresholds=args.confidence_thresholds,
        nms_iou_thresholds=args.nms_iou_thresholds,
        classifier_score_alphas=args.classifier_score_alphas,
        prototype_alphas=args.prototype_alphas,
        prototype_temperatures=args.prototype_temperatures,
        rejector_enabled_values=args.rejector_enabled_values,
    )
    if args.max_configs is not None:
        candidates = candidates[: max(0, args.max_configs)]
    if not candidates:
        raise SystemExit("No configuration candidates to evaluate.")

    original_config_text = config_path.read_text(encoding="utf-8") if config_path.exists() else None
    report_candidates = []
    try:
        for candidate_index, candidate in enumerate(candidates, start=1):
            print(f"[{candidate_index}/{len(candidates)}] {candidate['id']}", flush=True)
            write_submission_config(config_path, candidate["config"])
            report_candidates.append(
                evaluate_candidate(
                    candidate=candidate,
                    annotations_path=annotations_path,
                    submission_dir=submission_dir,
                    fold_inputs=fold_inputs,
                    workspace=workspace / "predictions",
                    iou_threshold=args.iou_threshold,
                    python_executable=args.python_executable.resolve() if args.python_executable else None,
                    pythonpath_entries=[path.resolve() for path in args.pythonpath],
                )
            )
    finally:
        restore_submission_config(config_path, original_config_text)

    best_candidate = max(report_candidates, key=lambda item: item["aggregate"]["combined_score_mean"])
    report = {
        "annotations_path": str(annotations_path),
        "images_dir": str(images_dir),
        "submission_dir": str(submission_dir),
        "cv_manifest": str(cv_manifest_path),
        "candidate_count": len(report_candidates),
        "best_candidate_id": best_candidate["id"],
        "best_combined_score_mean": best_candidate["aggregate"]["combined_score_mean"],
        "candidates": report_candidates,
    }
    save_json(args.output.resolve(), report)

    print(f"output={args.output.resolve()}")
    print(f"best_candidate={best_candidate['id']}")
    print(f"best_combined_score_mean={best_candidate['aggregate']['combined_score_mean']:.6f}")


def resolve_manifest_path(path: Path) -> Path:
    if path.is_dir():
        return path / "manifest.json"
    return path


def normalize_split_entry(root: Path, entry: dict) -> dict:
    split_path = root / str(entry["path"])
    return {
        "path": split_path.resolve(),
        "repeat_index": int(entry["repeat_index"]),
        "fold_index": int(entry["fold_index"]),
    }


def stage_fold_inputs(
    split_entries: list[dict],
    images_by_id: dict[int, dict],
    images_dir: Path,
    workspace: Path,
    copy_images: bool,
) -> list[dict]:
    workspace.mkdir(parents=True, exist_ok=True)
    fold_inputs = []
    for entry in split_entries:
        split_payload = load_json(entry["path"])
        fold_dir = workspace / f"repeat_{entry['repeat_index']:02d}_fold_{entry['fold_index']:02d}"
        if fold_dir.exists():
            shutil.rmtree(fold_dir)
        fold_dir.mkdir(parents=True, exist_ok=True)

        val_image_ids = [int(image_id) for image_id in split_payload.get("val_image_ids", [])]
        for image_id in val_image_ids:
            image_record = images_by_id[image_id]
            source_path = resolve_image_path(images_dir, str(image_record["file_name"]))
            destination_path = fold_dir / Path(str(image_record["file_name"])).name
            link_or_copy(source_path, destination_path, copy_images=copy_images)

        fold_inputs.append(
            {
                "split_path": entry["path"],
                "repeat_index": entry["repeat_index"],
                "fold_index": entry["fold_index"],
                "input_dir": fold_dir,
            }
        )
    return fold_inputs


def link_or_copy(source_path: Path, destination_path: Path, copy_images: bool) -> None:
    destination_path.parent.mkdir(parents=True, exist_ok=True)
    if destination_path.exists():
        destination_path.unlink()
    if copy_images:
        shutil.copy2(source_path, destination_path)
        return
    try:
        destination_path.hardlink_to(source_path)
    except OSError:
        shutil.copy2(source_path, destination_path)


def load_submission_config(path: Path) -> dict:
    if not path.exists():
        return {}
    return load_json(path)


def clone_config(config: dict) -> dict:
    return load_json_text(save_to_text(config))


def save_to_text(payload: dict) -> str:
    import json

    return json.dumps(payload, indent=2, sort_keys=True)


def load_json_text(text: str) -> dict:
    import json

    return json.loads(text)


def deep_merge(base: dict, override: dict) -> dict:
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(base.get(key), dict):
            deep_merge(base[key], value)
            continue
        base[key] = value
    return base


def build_candidates(
    base_config: dict,
    confidence_thresholds: list[float] | None,
    nms_iou_thresholds: list[float] | None,
    classifier_score_alphas: list[float] | None,
    prototype_alphas: list[float] | None,
    prototype_temperatures: list[float] | None,
    rejector_enabled_values: list[int] | None,
) -> list[dict]:
    current_confidence = float(base_config.get("confidence_threshold", 0.2))
    current_nms_iou = float(base_config.get("onnx", {}).get("nms_iou_threshold", 0.5))
    current_alpha = float(base_config.get("classifier", {}).get("score_alpha", 0.5))
    current_prototype_alpha = float(base_config.get("classifier", {}).get("prototype_alpha", 0.0))
    current_prototype_temperature = float(base_config.get("classifier", {}).get("prototype_temperature", 0.1))
    current_rejector_enabled = 1 if bool(base_config.get("classifier", {}).get("rejector_enabled", False)) else 0

    confidence_values = confidence_thresholds or [current_confidence]
    nms_values = nms_iou_thresholds or [current_nms_iou]
    alpha_values = classifier_score_alphas or [current_alpha]
    prototype_alpha_values = prototype_alphas or [current_prototype_alpha]
    prototype_temperature_values = prototype_temperatures or [current_prototype_temperature]
    rejector_values = rejector_enabled_values or [current_rejector_enabled]

    candidates = []
    for confidence_threshold, nms_iou_threshold, classifier_score_alpha, prototype_alpha, prototype_temperature, rejector_enabled in itertools.product(
        confidence_values,
        nms_values,
        alpha_values,
        prototype_alpha_values,
        prototype_temperature_values,
        rejector_values,
    ):
        candidate_config = clone_config(base_config)
        deep_merge(
            candidate_config,
            {
                "confidence_threshold": confidence_threshold,
                "onnx": {
                    "nms_iou_threshold": nms_iou_threshold,
                },
                "classifier": {
                    "score_alpha": classifier_score_alpha,
                    "prototype_alpha": prototype_alpha,
                    "prototype_temperature": prototype_temperature,
                    "rejector_enabled": bool(rejector_enabled),
                },
            },
        )
        candidates.append(
            {
                "id": (
                    f"conf_{format_decimal(confidence_threshold)}"
                    f"__nms_{format_decimal(nms_iou_threshold)}"
                    f"__alpha_{format_decimal(classifier_score_alpha)}"
                    f"__proto_{format_decimal(prototype_alpha)}"
                    f"__ptemp_{format_decimal(prototype_temperature)}"
                    f"__reject_{int(bool(rejector_enabled))}"
                ),
                "config": candidate_config,
                "settings": {
                    "confidence_threshold": confidence_threshold,
                    "nms_iou_threshold": nms_iou_threshold,
                    "classifier_score_alpha": classifier_score_alpha,
                    "prototype_alpha": prototype_alpha,
                    "prototype_temperature": prototype_temperature,
                    "rejector_enabled": bool(rejector_enabled),
                },
            }
        )
    return candidates


def format_decimal(value: float) -> str:
    return f"{float(value):.4f}".rstrip("0").rstrip(".").replace(".", "p")


def write_submission_config(path: Path, config: dict) -> None:
    path.write_text(save_to_text(config) + "\n", encoding="utf-8")


def restore_submission_config(path: Path, original_text: str | None) -> None:
    if original_text is None:
        if path.exists():
            path.unlink()
        return
    path.write_text(original_text, encoding="utf-8")


def evaluate_candidate(
    candidate: dict,
    annotations_path: Path,
    submission_dir: Path,
    fold_inputs: list[dict],
    workspace: Path,
    iou_threshold: float,
    python_executable: Path | None,
    pythonpath_entries: list[Path],
) -> dict:
    candidate_workspace = workspace / candidate["id"]
    candidate_workspace.mkdir(parents=True, exist_ok=True)

    fold_reports = []
    for fold in fold_inputs:
        fold_label = f"repeat_{fold['repeat_index']:02d}_fold_{fold['fold_index']:02d}"
        predictions_output = candidate_workspace / f"{fold_label}_predictions.json"
        inference_seconds = run_submission(
            submission_dir=submission_dir,
            image_dir=fold["input_dir"],
            predictions_output=predictions_output,
            python_executable=python_executable,
            pythonpath_entries=pythonpath_entries,
        )
        predictions = load_json(predictions_output)
        summary = evaluate_predictions(
            annotations_path=annotations_path,
            split_path=fold["split_path"],
            split_name="val",
            predictions=predictions,
            iou_threshold=iou_threshold,
        )
        summary.update(
            {
                "repeat_index": fold["repeat_index"],
                "fold_index": fold["fold_index"],
                "fold_label": fold_label,
                "input_dir": str(fold["input_dir"]),
                "predictions_output": str(predictions_output),
                "inference_seconds": round(inference_seconds, 6),
                "average_inference_seconds": round(inference_seconds / max(1, summary["image_count"]), 6),
            }
        )
        fold_reports.append(summary)

    return {
        "id": candidate["id"],
        "settings": candidate["settings"],
        "aggregate": aggregate_fold_reports(fold_reports),
        "folds": fold_reports,
    }


def aggregate_fold_reports(fold_reports: list[dict]) -> dict:
    detection_values = [float(report["detection_ap50"]) for report in fold_reports]
    classification_values = [float(report["classification_map50"]) for report in fold_reports]
    combined_values = [float(report["combined_score"]) for report in fold_reports]
    timing_values = [float(report["average_inference_seconds"]) for report in fold_reports]

    return {
        "fold_count": len(fold_reports),
        "detection_ap50_mean": round(statistics.mean(detection_values), 6),
        "detection_ap50_std": round(statistics.pstdev(detection_values), 6) if len(detection_values) > 1 else 0.0,
        "classification_map50_mean": round(statistics.mean(classification_values), 6),
        "classification_map50_std": round(statistics.pstdev(classification_values), 6)
        if len(classification_values) > 1
        else 0.0,
        "combined_score_mean": round(statistics.mean(combined_values), 6),
        "combined_score_std": round(statistics.pstdev(combined_values), 6) if len(combined_values) > 1 else 0.0,
        "average_inference_seconds_mean": round(statistics.mean(timing_values), 6),
        "average_inference_seconds_std": round(statistics.pstdev(timing_values), 6) if len(timing_values) > 1 else 0.0,
    }


if __name__ == "__main__":
    main()
